SHELL=/bin/bash -O extglob -c
FC=gfortran# compiler
SDIR=./src# source file directory
ODIR=./obj# directory to store .o, .mod, .obj files generated by compilation

OPTIONS=-O3 -J$(ODIR)
_OBJ=constants.o \
param.o \
datatypes.o \
globvar.o \
summary_m.o \
material_rates_m.o \
output_m.o \
input_m.o \
kernel_m.o \
flink_lisk_m.o \
single_step_m.o \
time_integration_m.o \
main.o \

OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

sph: $(OBJ)
	$(FC) -o $@ $^ $(OPTIONS)

clean:
	@rm $(ODIR)/*(*.o|*.obj|*.mod)

$(ODIR)/%.o: $(SDIR)/%.f90
	@if [ ! -d $(ODIR) ]; then \
		mkdir $(ODIR); \
	fi
	$(FC) -c -o $@ $< $(OPTIONS)
